#!/usr/bin/perl
use warnings;
use strict;

die "program x y density" unless (scalar(@ARGV) == 3);

my ($x, $y, $density) = @ARGV;

my ($a, $b, $c) = ('0', '1', '7');

print "$y";
print "$a";
print "$b";
print "$c";
print "\n";

for (my $i = 0; $i < $y; $i++) 
{
	for (my $j = 0; $j < $x; $j++) 
	{
		if (int(rand($y) * 2) < $density) 
		{
			print "$b";
		}
		else 
		{
			print "$a";
		}
	}
	print "\n";
}
